import type { Metadata } from "next";
import {  Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope", // Optional, for CSS variable
  display: "swap", // Improves font loading
  weight: ["400", "500", "600", "700"], // Include the weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={manrope.variable}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
